version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always

  backend:
    build: ./backend
    container_name: node-backend
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always